---
name: Molecule CI
on:
  push:
    branches:
      - 'main'

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario: [default,blue-green]      
        os: [centos-8, debian-10, fedora-34, oraclelinux-8, ubuntu-20.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: "${{ github.repository }}"

      - name: Get no_value_key from secrets.NO_VALUE_KEY
        env: # as an environment variable
          NO_VALUE_KEY: ${{ secrets.NO_VALUE_KEY }}                         
        run: |
          echo "The GitHub Action Secret will be masked:  "
          echo ${{ secrets.NO_VALUE_KEY }}
          #echo "Trick to echo GitHub Actions Secret:  "
          #echo ${{secrets.NO_VALUE_KEY}} | sed 's/./& /g'          

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ansible.
        run: pip3 install ansible          

      - name: Install molecule[docker].
        run: pip3 install molecule[docker]

      - name: Install yamllint.
        run: pip3 install yamllint

      - name: Install ansible-lint.
        run: pip3 install ansible-lint    
 
      - name: Molecule
        uses: gofrolist/molecule-action@v2
        with:
          molecule_options: --debug --base-config ../../tests/molecule/base.yml
          molecule_command: test
          molecule_working_dir: ${{ github.repository }}
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
      - name: Run Molecule tests.
        run: molecule -verbose test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
        working-directory: "${{ github.repository }}"          
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true          